# Generated by Django 5.1.1 on 2025-02-10 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ordered_placed_orderplaced_ordered_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Cart',
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.CharField(choices=[('Lumbini', 'Lumbini'), ('Bagmati', 'Bagmati'), ('Madhesh', 'Madhesh'), ('Koshi', 'Koshi'), ('Gandaki', 'Gandaki'), ('Sudurpashchim', 'Sudurpashchim'), ('Karnali', 'Karnali')], max_length=70),
        ),
    ]
